# This file is part of m2code-gen <https://github.com/roma-glushko/m2code-gen>
# @author Roman Glushko <https://github.com/roma-glushko>

templatePath: frontend-plugin-new
files:
  'Plugin/{{domain}}/{{pluginClass}}.php':
    validator: ''
    applier: 'applier.copyFile'
  'etc/frontend/di.xml':
    validator: ''
    applier: 'applier.mergeXml'