# This file is part of m2code-gen <https://github.com/roma-glushko/m2code-gen>
# @author Roman Glushko <https://github.com/roma-glushko>

templatePath: module-new
files:
  'etc/module.xml':
    validator: ''
  'composer.json':
    validator: ''
  'registration.php':
    validator: ''