# This file is part of m2code-gen <https://github.com/roma-glushko/m2code-gen>
# @author Roman Glushko <https://github.com/roma-glushko>
parameters:
  env.rootPath: 'will be configured during run-time'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Atwix\:
    resource: '../Atwix/*'

  Atwix\System\Application:
    autowire: false

  Atwix\System\Filesystem\DirectoryLocator:
    arguments: ['%env.rootPath%']

  applier.copyFile: '@Atwix\Applier\CopyFileApplier'

  applier.mergeXml: '@Atwix\Applier\MergeXmlApplier'

  Symfony\Component\Filesystem\Filesystem: ~

